name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          echo "${{ vars.EC2_KNOWN_HOST }}" > ~/.ssh/known_hosts

      - name: Deploy code to EC2
        run: |
          ssh -i ~/.ssh/ec2_key ec2-user@${{ vars.EC2_HOST }} "
            cd /home/ec2-user/learn-github-actions &&
            git pull
          "
