name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy code to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ vars.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/learn-github-actions
            git pull
            DB_URL=${{ secrets.DB_URL }} \
            JWT_SECRET=${{ secrets.JWT_SECRET }} \
            MY_SECRET=789 \
            npm ci
            node main.js
