name: Prettier Check

on:
  push:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install devDependencies
        run: npm ci --omit=prod

      - name: Run Prettier check
        run: npx prettier --check --ignore-unknown .
